name: Auto Update PRs with autoupdate Label

on:
  push:
    branches:
      - master

jobs:
  auto-update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Auto Updater"
          git config --global user.email "m.ehmet.tosun@gmail.com"

      - name: Get open PRs with autoupdate label
        id: get_prs
        run: |
          # Use GitHub CLI to fetch open PRs with the autoupdate label
          PRS=$(gh pr list --label "autoupdate" --state open --json number,headRefName --jq '.[].headRefName')

          if [ -z "$PRS" ]; then
            echo "No open PRs found with the autoupdate label."
            exit 0
          fi

          echo "prs=$PRS" >> $GITHUB_OUTPUT

      - name: Update each PR branch
        if: steps.get_prs.outputs.prs != ''
        run: |
          for branch in ${{ steps.get_prs.outputs.prs }}
          do
            echo "Updating branch: $branch"

            git fetch origin
            git checkout $branch || git checkout -b $branch origin/$branch

            # Merge latest master
            git merge origin/master -m "Auto merge from master"

            # Push updated branch
            git push origin $branch
          done
        env:
          GITHUB_TOKEN: ${{ secrets.G1THUB_TOKEN }}
